### ISSUE TITLE
The metrics has iptable rules that no longer exist

### ISSUE THREAD

**Issue by 504274990** [kbknapp/iptables_exporter#1]
**Version:**
v0.1.1
**Describe the bug**
from the metrics，the total number of my iptables rules keeps growing，as shown below，the promql is sum(iptables_rules_total).
![image](https://user-images.githubusercontent.com/13415530/117944709-2251d800-b340-11eb-9d92-2b4beade1066.png)

I found that the chain of the growing iptables_rules_total metrics is KUBE-NWPLCY*, but I only saw a chain named KUBE-NWPLCY-IYDORQLYDGN26QIB on the machine.
 I observed this KUBE-NWPLCY* chain on this machine. After a while, this KUBE-NWPLCY* chain will be rebuilt and its name changed. But iptables_exporter added new chain metrics,  did not delete the old chain metrics.   
When I restarted the iptables-exporter container, the metrics will be consistent with the iptables chain on the machine, but after a period of time, the things described above will be repeated.

![image](https://user-images.githubusercontent.com/13415530/117945985-73ae9700-b341-11eb-979d-219a83cfc0fe.png)
![image](https://user-images.githubusercontent.com/13415530/117945283-c3409300-b340-11eb-97df-c62059571bb2.png)

**Expected behavior**
The metrics of iptables_exporter are consistent with the real iptables chains on the machine，the non-existent chain on the machine needs to be deleted in iptables-exporter.

**Comment by kbknapp** [comment]
Were those no longer existing chains in the exported metrics, or just remnants in a Prometheus database? I.e. if you look at the raw metrics exported, do those chains still exist?

I haven't reproduced this, but I'm assuming what your Grafana dashboard is seeing is remnants in the Prometheus database as I'm also assuming that graph is not scraping the raw metrics provided `iptables_exporter`. So I think what's happening is Prometheus is scraping the exporter, saving the chains metrics, and then whenever those chains go away Prometheus isn't cleaning them out.

There isn't a way for `iptables_exporter` to delete entries from the Prometheus database. I'll  test this on my end too, but if it's determined to be the Prometheus issue I described above, I'll close this issue.

There could be an argument made to have a flag that allows combining "ephemeral" chains based on some wildcard, i.e. `KUBE-NWPLCY-*` in your case, but that should be a separate feature request.
