### ISSUE TITLE
Add support for iptables-legacy

### ISSUE THREAD

**Issue by virtualtam** [kbknapp/iptables_exporter#4]
Hi @kbknapp , and thanks for maintaining this Prometheus exporter :wave: 

---

For those of us who have yet to migrate to `nftables` to manage network routing, we may end up in a situation where:

- part of the routing is managed through `iptables` / `nftables` (e.g. when using fail2ban)
- part of the routing is managed through `iptables-legacy` (e.g. when using a frontend such as Ferm or Shorewall)

Reference:

- https://wiki.nftables.org/wiki-nftables/index.php/Adoption 
- https://wiki.debian.org/iptables (I noticed the "loss" of the metrics while migrating Debian hosts from Buster to Bullseye)

For such situations, it would be convenient to be able to gather and expose metrics for rules managed by both `iptables` and `iptables-legacy`.

This could be implemented by adding a `--legacy` or `--iptables-legacy` boolean flag, and either:

1. running two instances of the exporter, and defining two separate Prometheus scrape jobs
2. running a single instance of the exporter, and prefixing legacy metrics with `iptables_legacy_`

Both approaches may be:

- brittle, as administrators may choose to disable `nftables` usage and re-alias `iptables` commands to their `iptables-legacy` counterparts (e.g. as shown in Debian docs)
- of limited use in time, as people are likely to migrate their configuration to `nftables` (or any suitable frontend)

---

Please let me know if there is interest in adding such a feature to the exporter, and which of the approaches mentioned above would be preferred so I can submit a PR with the corresponding changes :)

(As a quick fix, I'm running two instances of a custom version of the exporter built from https://github.com/virtualtam/iptables_exporter/tree/wip/iptables-legacy to expose metrics for both backends)

**Comment by kbknapp** [comment]
I appreciate the detailed write-up but I'm not 100% sure how to handle it as the Ubuntu systems I have handy to test all present different (or rather no) output with `iptables-legacy-save` than `iptables-save`.

I'm 100% open to a PR in either of the two options you've listed, I'd lean towards option 2 if I really had to pick.

Alternatively if you'd like to paste the output of both `iptables-save --counters` and `iptables-legacy-save --counters` I might be able to give some better insight.

**Comment by virtualtam** [comment]
AFAIK, on recent systems, the `iptables` commands are provided as a compatibility layer for the underlying `nftables` commands, and the output for `iptables-save` and `iptables-legacy-save` commands should use the same format.

For reference, please find attached:

- [system-info.txt](https://github.com/kbknapp/iptables_exporter/files/10098620/system-info.txt): relevant information regarding the Debian host and `iptables` packages
- [iptables-legacy-save.txt](https://github.com/kbknapp/iptables_exporter/files/10098618/iptables-legacy-save.txt): dump of the rules managed by the Ferm frontend for `iptables-legacy`
- [iptables-save.txt](https://github.com/kbknapp/iptables_exporter/files/10098619/iptables-save.txt): dump of the rules managed by fail2ban

I agree that optionally running a second asynchronous collector for `iptables_legacy_*` metrics would be preferable, as it would explicitly show admins where the metrics come from, and avoid running the exporter twice :)

**Comment by kbknapp** [comment]
Very interesting! Yeah on the system I tested on `iptables-save` gave back normal results and `iptables-legacy-save` ran, reported a successful exit but didn't contain any output.

Since the output examples you gave have the same format adding support for `iptables-legacy-save` should be pretty straight forward and actually kind of ties in with #3 if you squint and view each of these as a sort of a "scrape target" that could be enabled/disabled.

I'm not sure how much time I'll have to put into this but I should be able to take a swing at adding this this weekend since it appears pretty straight forward (`iptables-legacy-save` only. Adding `ip6tables` will probably be more work and take longer).

**Comment by virtualtam** [comment]
Thanks!
I'll give a spin to #6 (and #3) on a couple hosts to test the `iptables` and `iptables-legacy` targets :+1:
