### ISSUE TITLE
Map iptables comments to prometheus labels

### ISSUE THREAD

**Issue by hrdflt** [kbknapp/iptables_exporter#7]
First thanks for your work. Great tool!

### Context
The metrics `iptables_rule_bytes_total` or `iptables_rule_packets_total` suffer from high label cardinality issue with the `rule` label when scraping large fleets of servers who have similar rules (in terms of ports and accept/reject/deny) but have unique interface name and source/dest network matchers.

To reduce label value cardinality in this scenario with the current implementation one has to either drop the `rule` label or mangle it in some way.

### Request
Implement mapping of iptables comments to prometheus labels.

For example, an iptables rule which contains:
```
-m comment --comment export
```
would map to `{_comment="export"}`

This allows the operator to then do things like dropping the `rule` label and creating more common naming conventions for `rule`'s which suffer from high cardinality across a fleet of servers.

For reference there is a similar implementation here, although this seems to do some parsing and stripping (which is not what I'm after): https://pypi.org/project/iptables-exporter/

**Comment by kbknapp** [comment]
Interesting, that's a great suggestion! I'm not sure when exactly I'll have time to implement it, so if anyone wants to propose a PR I'd gladly take a look. I'll try to carve out some time this weekend - I imagine it'll be just some kind of regex matching against the rules so it shouldn't be too difficult.

**Comment by kbknapp** [comment]
I've started a draft PR (#8) - I'll see if I can find some time to finish it this weekend.

**Comment by kbknapp** [comment]
Found some spare time - I put the new release (v0.3.0) on crates.io and the releases page.
